# Generated by Django 3.2.6 on 2021-10-04 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211004_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nombre',
            field=models.CharField(blank=True, max_length=90, validators=[django.core.validators.MinLengthValidator(3, 'Nombre debe ser mayor a 3 caracteres.')]),
        ),
    ]
